### ISSUE TITLE
add_document.py 実行時のpineconeの「NameResolutionError」について

### ISSUE THREAD

**Issue by yugo-haruyama** [yoshidashingo/langchain-book#9]
**エラーの説明**
P341のadd_ document. pyの実行をした際に以下スクリーンショットのエラーが発生をしています。
どうやら、pineconeサービスに接続しようとした際に、そホスト名（controller.gcp-start.pinecone.io）を解決できないために発生しているそうです。

しかし、.envに記載しているAPIキー及びindexも間違っておらず、原因が不明な状況です。
何か考えられる懸念点はありますでしょうか？

**書籍の内容以外で実施したこと**

念のためライブラリを指定されたバージョンに再インストールしました。
あとは、pinecone側のindexsの再作成や、APIキーの再発行なども試しました。

**環境**

AWS Cloud9

**スクリーンショット**

```
(main) $ python add_document.py seo_book.pdf
2023-12-06 03:14:24,481 [INFO] Loaded 1 documents
2023-12-06 03:14:24,491 [WARNING] Created a chunk of size 444, which is longer than the specified 300
2023-12-06 03:14:24,495 [WARNING] Created a chunk of size 633, which is longer than the specified 300
2023-12-06 03:14:24,496 [WARNING] Created a chunk of size 311, which is longer than the specified 300
2023-12-06 03:14:24,496 [WARNING] Created a chunk of size 399, which is longer than the specified 300
2023-12-06 03:14:24,497 [WARNING] Created a chunk of size 450, which is longer than the specified 300
2023-12-06 03:14:24,510 [INFO] Split 754 documents
2023-12-06 03:14:24,573 [WARNING] Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7f7bcdf688e0>: Failed to resolve 'controller.gcp-start.pinecone.io' ([Errno -2] Name or service not known)")': /databases
2023-12-06 03:14:24,575 [WARNING] Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7f7bcdf69c30>: Failed to resolve 'controller.gcp-start.pinecone.io' ([Errno -2] Name or service not known)")': /databases
2023-12-06 03:14:24,577 [WARNING] Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7f7bcdf6bd90>: Failed to resolve 'controller.gcp-start.pinecone.io' ([Errno -2] Name or service not known)")': /databases
Traceback (most recent call last):
  File "/home/ec2-user/environment/slackapp-chatgpt/.venv/lib/python3.10/site-packages/urllib3/connection.py", line 203, in _new_conn
    sock = connection.create_connection(
  File "/home/ec2-user/environment/slackapp-chatgpt/.venv/lib/python3.10/site-packages/urllib3/util/connection.py", line 60, in create_connection
    for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):
  File "/home/ec2-user/.pyenv/versions/3.10.13/lib/python3.10/socket.py", line 955, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -2] Name or service not known

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/ec2-user/environment/slackapp-chatgpt/.venv/lib/python3.10/site-packages/urllib3/connectionpool.py", line 791, in urlopen
    response = self._make_request(
  File "/home/ec2-user/environment/slackapp-chatgpt/.venv/lib/python3.10/site-packages/urllib3/connectionpool.py", line 492, in _make_request
    raise new_e
  File "/home/ec2-user/environment/slackapp-chatgpt/.venv/lib/python3.10/site-packages/urllib3/connectionpool.py", line 468, in _make_request
    self._validate_conn(conn)
  File "/home/ec2-user/environment/slackapp-chatgpt/.venv/lib/python3.10/site-packages/urllib3/connectionpool.py", line 1097, in _validate_conn
    conn.connect()
  File "/home/ec2-user/environment/slackapp-chatgpt/.venv/lib/python3.10/site-packages/urllib3/connection.py", line 611, in connect
    self.sock = sock = self._new_conn()
  File "/home/ec2-user/environment/slackapp-chatgpt/.venv/lib/python3.10/site-packages/urllib3/connection.py", line 210, in _new_conn
    raise NameResolutionError(self.host, self, e) from e
urllib3.exceptions.NameResolutionError: <urllib3.connection.HTTPSConnection object at 0x7f7bcdf69900>: Failed to resolve 'controller.gcp-start.pinecone.io' ([Errno -2] Name or service not known)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/ec2-user/environment/slackapp-chatgpt/add_document.py", line 41, in <module>
    vectorstore = initialize_vectorstore()
  File "/home/ec2-user/environment/slackapp-chatgpt/add_document.py", line 28, in initialize_vectorstore
    return Pinecone.from_existing_index(index_name, embeddings)
  File "/home/ec2-user/environment/slackapp-chatgpt/.venv/lib/python3.10/site-packages/langchain/vectorstores/pinecone.py", line 437, in from_existing_index
    pinecone_index = cls.get_pinecone_index(index_name, pool_threads)
  File "/home/ec2-user/environment/slackapp-chatgpt/.venv/lib/python3.10/site-packages/langchain/vectorstores/pinecone.py", line 354, in get_pinecone_index
    indexes = pinecone.list_indexes()  # checks if provided index exists
  File "/home/ec2-user/environment/slackapp-chatgpt/.venv/lib/python3.10/site-packages/pinecone/manage.py", line 185, in list_indexes
    response = api_instance.list_indexes()
  File "/home/ec2-user/environment/slackapp-chatgpt/.venv/lib/python3.10/site-packages/pinecone/core/client/api_client.py", line 776, in __call__
    return self.callable(self, *args, **kwargs)
  File "/home/ec2-user/environment/slackapp-chatgpt/.venv/lib/python3.10/site-packages/pinecone/core/client/api/index_operations_api.py", line 1130, in __list_indexes
    return self.call_with_http_info(**kwargs)
  File "/home/ec2-user/environment/slackapp-chatgpt/.venv/lib/python3.10/site-packages/pinecone/core/client/api_client.py", line 838, in call_with_http_info
    return self.api_client.call_api(
  File "/home/ec2-user/environment/slackapp-chatgpt/.venv/lib/python3.10/site-packages/pinecone/core/client/api_client.py", line 413, in call_api
    return self.__call_api(resource_path, method,
  File "/home/ec2-user/environment/slackapp-chatgpt/.venv/lib/python3.10/site-packages/pinecone/core/client/api_client.py", line 200, in __call_api
    response_data = self.request(
  File "/home/ec2-user/environment/slackapp-chatgpt/.venv/lib/python3.10/site-packages/pinecone/core/client/api_client.py", line 439, in request
    return self.rest_client.GET(url,
  File "/home/ec2-user/environment/slackapp-chatgpt/.venv/lib/python3.10/site-packages/pinecone/core/client/rest.py", line 236, in GET
    return self.request("GET", url,
  File "/home/ec2-user/environment/slackapp-chatgpt/.venv/lib/python3.10/site-packages/pinecone/core/client/rest.py", line 202, in request
    r = self.pool_manager.request(method, url,
  File "/home/ec2-user/environment/slackapp-chatgpt/.venv/lib/python3.10/site-packages/urllib3/_request_methods.py", line 110, in request
    return self.request_encode_url(
  File "/home/ec2-user/environment/slackapp-chatgpt/.venv/lib/python3.10/site-packages/urllib3/_request_methods.py", line 143, in request_encode_url
    return self.urlopen(method, url, **extra_kw)
  File "/home/ec2-user/environment/slackapp-chatgpt/.venv/lib/python3.10/site-packages/urllib3/poolmanager.py", line 443, in urlopen
    response = conn.urlopen(method, u.request_uri, **kw)
  File "/home/ec2-user/environment/slackapp-chatgpt/.venv/lib/python3.10/site-packages/urllib3/connectionpool.py", line 875, in urlopen
    return self.urlopen(
  File "/home/ec2-user/environment/slackapp-chatgpt/.venv/lib/python3.10/site-packages/urllib3/connectionpool.py", line 875, in urlopen
    return self.urlopen(
  File "/home/ec2-user/environment/slackapp-chatgpt/.venv/lib/python3.10/site-packages/urllib3/connectionpool.py", line 875, in urlopen
    return self.urlopen(
  File "/home/ec2-user/environment/slackapp-chatgpt/.venv/lib/python3.10/site-packages/urllib3/connectionpool.py", line 845, in urlopen
    retries = retries.increment(
  File "/home/ec2-user/environment/slackapp-chatgpt/.venv/lib/python3.10/site-packages/urllib3/util/retry.py", line 515, in increment
    raise MaxRetryError(_pool, url, reason) from reason  # type: ignore[arg-type]
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='controller.gcp-start.pinecone.io', port=443): Max retries exceeded with url: /databases (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7f7bcdf69900>: Failed to resolve 'controller.gcp-start.pinecone.io' ([Errno -2] Name or service not known)"))
(.venv) ec2-user:~/environment/slackapp-chatgpt (main) $ python add_document.py seo_book.pdf
2023-12-06 03:28:16,249 [INFO] Loaded 1 documents
2023-12-06 03:28:16,261 [WARNING] Created a chunk of size 444, which is longer than the specified 300
2023-12-06 03:28:16,264 [WARNING] Created a chunk of size 633, which is longer than the specified 300
2023-12-06 03:28:16,265 [WARNING] Created a chunk of size 311, which is longer than the specified 300
2023-12-06 03:28:16,265 [WARNING] Created a chunk of size 399, which is longer than the specified 300
2023-12-06 03:28:16,266 [WARNING] Created a chunk of size 450, which is longer than the specified 300
2023-12-06 03:28:16,279 [INFO] Split 754 documents
2023-12-06 03:28:16,301 [WARNING] Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7fea1af78340>: Failed to resolve 'controller.gcp-start.pinecone.io' ([Errno -2] Name or service not known)")': /databases
2023-12-06 03:28:16,303 [WARNING] Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7fea1b011b10>: Failed to resolve 'controller.gcp-start.pinecone.io' ([Errno -2] Name or service not known)")': /databases
2023-12-06 03:28:16,305 [WARNING] Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7fea1b013550>: Failed to resolve 'controller.gcp-start.pinecone.io' ([Errno -2] Name or service not known)")': /databases
Traceback (most recent call last):
  File "/home/ec2-user/environment/slackapp-chatgpt/.venv/lib/python3.10/site-packages/urllib3/connection.py", line 203, in _new_conn
    sock = connection.create_connection(
  File "/home/ec2-user/environment/slackapp-chatgpt/.venv/lib/python3.10/site-packages/urllib3/util/connection.py", line 60, in create_connection
    for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):
  File "/home/ec2-user/.pyenv/versions/3.10.13/lib/python3.10/socket.py", line 955, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -2] Name or service not known

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/ec2-user/environment/slackapp-chatgpt/.venv/lib/python3.10/site-packages/urllib3/connectionpool.py", line 791, in urlopen
    response = self._make_request(
  File "/home/ec2-user/environment/slackapp-chatgpt/.venv/lib/python3.10/site-packages/urllib3/connectionpool.py", line 492, in _make_request
    raise new_e
  File "/home/ec2-user/environment/slackapp-chatgpt/.venv/lib/python3.10/site-packages/urllib3/connectionpool.py", line 468, in _make_request
    self._validate_conn(conn)
  File "/home/ec2-user/environment/slackapp-chatgpt/.venv/lib/python3.10/site-packages/urllib3/connectionpool.py", line 1097, in _validate_conn
    conn.connect()
  File "/home/ec2-user/environment/slackapp-chatgpt/.venv/lib/python3.10/site-packages/urllib3/connection.py", line 611, in connect
    self.sock = sock = self._new_conn()
  File "/home/ec2-user/environment/slackapp-chatgpt/.venv/lib/python3.10/site-packages/urllib3/connection.py", line 210, in _new_conn
    raise NameResolutionError(self.host, self, e) from e
urllib3.exceptions.NameResolutionError: <urllib3.connection.HTTPSConnection object at 0x7fea1b012860>: Failed to resolve 'controller.gcp-start.pinecone.io' ([Errno -2] Name or service not known)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/ec2-user/environment/slackapp-chatgpt/add_document.py", line 41, in <module>
    vectorstore = initialize_vectorstore()
  File "/home/ec2-user/environment/slackapp-chatgpt/add_document.py", line 28, in initialize_vectorstore
    return Pinecone.from_existing_index(index_name, embeddings)
  File "/home/ec2-user/environment/slackapp-chatgpt/.venv/lib/python3.10/site-packages/langchain/vectorstores/pinecone.py", line 437, in from_existing_index
    pinecone_index = cls.get_pinecone_index(index_name, pool_threads)
  File "/home/ec2-user/environment/slackapp-chatgpt/.venv/lib/python3.10/site-packages/langchain/vectorstores/pinecone.py", line 354, in get_pinecone_index
    indexes = pinecone.list_indexes()  # checks if provided index exists
  File "/home/ec2-user/environment/slackapp-chatgpt/.venv/lib/python3.10/site-packages/pinecone/manage.py", line 185, in list_indexes
    response = api_instance.list_indexes()
  File "/home/ec2-user/environment/slackapp-chatgpt/.venv/lib/python3.10/site-packages/pinecone/core/client/api_client.py", line 776, in __call__
    return self.callable(self, *args, **kwargs)
  File "/home/ec2-user/environment/slackapp-chatgpt/.venv/lib/python3.10/site-packages/pinecone/core/client/api/index_operations_api.py", line 1130, in __list_indexes
    return self.call_with_http_info(**kwargs)
  File "/home/ec2-user/environment/slackapp-chatgpt/.venv/lib/python3.10/site-packages/pinecone/core/client/api_client.py", line 838, in call_with_http_info
    return self.api_client.call_api(
  File "/home/ec2-user/environment/slackapp-chatgpt/.venv/lib/python3.10/site-packages/pinecone/core/client/api_client.py", line 413, in call_api
    return self.__call_api(resource_path, method,
  File "/home/ec2-user/environment/slackapp-chatgpt/.venv/lib/python3.10/site-packages/pinecone/core/client/api_client.py", line 200, in __call_api
    response_data = self.request(
  File "/home/ec2-user/environment/slackapp-chatgpt/.venv/lib/python3.10/site-packages/pinecone/core/client/api_client.py", line 439, in request
    return self.rest_client.GET(url,
  File "/home/ec2-user/environment/slackapp-chatgpt/.venv/lib/python3.10/site-packages/pinecone/core/client/rest.py", line 236, in GET
    return self.request("GET", url,
  File "/home/ec2-user/environment/slackapp-chatgpt/.venv/lib/python3.10/site-packages/pinecone/core/client/rest.py", line 202, in request
    r = self.pool_manager.request(method, url,
  File "/home/ec2-user/environment/slackapp-chatgpt/.venv/lib/python3.10/site-packages/urllib3/_request_methods.py", line 110, in request
    return self.request_encode_url(
  File "/home/ec2-user/environment/slackapp-chatgpt/.venv/lib/python3.10/site-packages/urllib3/_request_methods.py", line 143, in request_encode_url
    return self.urlopen(method, url, **extra_kw)
  File "/home/ec2-user/environment/slackapp-chatgpt/.venv/lib/python3.10/site-packages/urllib3/poolmanager.py", line 443, in urlopen
    response = conn.urlopen(method, u.request_uri, **kw)
  File "/home/ec2-user/environment/slackapp-chatgpt/.venv/lib/python3.10/site-packages/urllib3/connectionpool.py", line 875, in urlopen
    return self.urlopen(
  File "/home/ec2-user/environment/slackapp-chatgpt/.venv/lib/python3.10/site-packages/urllib3/connectionpool.py", line 875, in urlopen
    return self.urlopen(
  File "/home/ec2-user/environment/slackapp-chatgpt/.venv/lib/python3.10/site-packages/urllib3/connectionpool.py", line 875, in urlopen
    return self.urlopen(
  File "/home/ec2-user/environment/slackapp-chatgpt/.venv/lib/python3.10/site-packages/urllib3/connectionpool.py", line 845, in urlopen
    retries = retries.increment(
  File "/home/ec2-user/environment/slackapp-chatgpt/.venv/lib/python3.10/site-packages/urllib3/util/retry.py", line 515, in increment
    raise MaxRetryError(_pool, url, reason) from reason  # type: ignore[arg-type]
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='controller.gcp-start.pinecone.io', port=443): Max retries exceeded with url: /databases (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7fea1b012860>: Failed to resolve 'controller.gcp-start.pinecone.io' ([Errno -2] Name or service not known)"))
(.venv) ec2-user:~/environment/slackapp-chatgpt (main) $ python add_document.py seo_book.pdf
Traceback (most recent call last):
  File "/home/ec2-user/environment/slackapp-chatgpt/add_document.py", line 34, in <module>
    raw_docs = loader.load()
  File "/home/ec2-user/environment/slackapp-chatgpt/.venv/lib/python3.10/site-packages/langchain/document_loaders/unstructured.py", line 86, in load
    elements = self._get_elements()
  File "/home/ec2-user/environment/slackapp-chatgpt/.venv/lib/python3.10/site-packages/langchain/document_loaders/pdf.py", line 59, in _get_elements
    return partition_pdf(filename=self.file_path, **self.unstructured_kwargs)
  File "/home/ec2-user/environment/slackapp-chatgpt/.venv/lib/python3.10/site-packages/unstructured/documents/elements.py", line 242, in wrapper
    elements = func(*args, **kwargs)
  File "/home/ec2-user/environment/slackapp-chatgpt/.venv/lib/python3.10/site-packages/unstructured/file_utils/filetype.py", line 541, in wrapper
    elements = func(*args, **kwargs)
  File "/home/ec2-user/environment/slackapp-chatgpt/.venv/lib/python3.10/site-packages/unstructured/chunking/title.py", line 197, in wrapper
    elements = func(*args, **kwargs)
  File "/home/ec2-user/environment/slackapp-chatgpt/.venv/lib/python3.10/site-packages/unstructured/partition/pdf.py", line 130, in partition_pdf
    return partition_pdf_or_image(
  File "/home/ec2-user/environment/slackapp-chatgpt/.venv/lib/python3.10/site-packages/unstructured/partition/pdf.py", line 209, in partition_pdf_or_image
    last_modification_date = get_the_last_modification_date_pdf_or_img(
  File "/home/ec2-user/environment/slackapp-chatgpt/.venv/lib/python3.10/site-packages/unstructured/partition/pdf.py", line 166, in get_the_last_modification_date_pdf_or_img
    last_modification_date = get_last_modified_date(filename=filename)
  File "/home/ec2-user/environment/slackapp-chatgpt/.venv/lib/python3.10/site-packages/unstructured/partition/common.py", line 81, in get_last_modified_date
    modify_date = datetime.fromtimestamp(os.path.getmtime(filename))
  File "/home/ec2-user/.pyenv/versions/3.10.13/lib/python3.10/genericpath.py", line 55, in getmtime
    return os.stat(filename).st_mtime
FileNotFoundError: [Errno 2] No such file or directory: 'seo_book.pdf'
(.venv) ec2-user:~/environment/slackapp-chatgpt (main) $ python add_document.py seo_book.pdf
2023-12-06 03:38:39,930 [INFO] Loaded 1 documents
2023-12-06 03:38:39,941 [WARNING] Created a chunk of size 444, which is longer than the specified 300
2023-12-06 03:38:39,944 [WARNING] Created a chunk of size 633, which is longer than the specified 300
2023-12-06 03:38:39,945 [WARNING] Created a chunk of size 311, which is longer than the specified 300
2023-12-06 03:38:39,945 [WARNING] Created a chunk of size 399, which is longer than the specified 300
2023-12-06 03:38:39,946 [WARNING] Created a chunk of size 450, which is longer than the specified 300
2023-12-06 03:38:39,959 [INFO] Split 754 documents
2023-12-06 03:38:39,981 [WARNING] Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7f527f8f88e0>: Failed to resolve 'controller.gcp-start.pinecone.io' ([Errno -2] Name or service not known)")': /databases
2023-12-06 03:38:39,983 [WARNING] Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7f527f8f9c30>: Failed to resolve 'controller.gcp-start.pinecone.io' ([Errno -2] Name or service not known)")': /databases
2023-12-06 03:38:39,984 [WARNING] Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7f527f8fbd90>: Failed to resolve 'controller.gcp-start.pinecone.io' ([Errno -2] Name or service not known)")': /databases
Traceback (most recent call last):
  File "/home/ec2-user/environment/slackapp-chatgpt/.venv/lib/python3.10/site-packages/urllib3/connection.py", line 203, in _new_conn
    sock = connection.create_connection(
  File "/home/ec2-user/environment/slackapp-chatgpt/.venv/lib/python3.10/site-packages/urllib3/util/connection.py", line 60, in create_connection
    for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):
  File "/home/ec2-user/.pyenv/versions/3.10.13/lib/python3.10/socket.py", line 955, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -2] Name or service not known

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/ec2-user/environment/slackapp-chatgpt/.venv/lib/python3.10/site-packages/urllib3/connectionpool.py", line 791, in urlopen
    response = self._make_request(
  File "/home/ec2-user/environment/slackapp-chatgpt/.venv/lib/python3.10/site-packages/urllib3/connectionpool.py", line 492, in _make_request
    raise new_e
  File "/home/ec2-user/environment/slackapp-chatgpt/.venv/lib/python3.10/site-packages/urllib3/connectionpool.py", line 468, in _make_request
    self._validate_conn(conn)
  File "/home/ec2-user/environment/slackapp-chatgpt/.venv/lib/python3.10/site-packages/urllib3/connectionpool.py", line 1097, in _validate_conn
    conn.connect()
  File "/home/ec2-user/environment/slackapp-chatgpt/.venv/lib/python3.10/site-packages/urllib3/connection.py", line 611, in connect
    self.sock = sock = self._new_conn()
  File "/home/ec2-user/environment/slackapp-chatgpt/.venv/lib/python3.10/site-packages/urllib3/connection.py", line 210, in _new_conn
    raise NameResolutionError(self.host, self, e) from e
urllib3.exceptions.NameResolutionError: <urllib3.connection.HTTPSConnection object at 0x7f527f8f9900>: Failed to resolve 'controller.gcp-start.pinecone.io' ([Errno -2] Name or service not known)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/ec2-user/environment/slackapp-chatgpt/add_document.py", line 41, in <module>
    vectorstore = initialize_vectorstore()
  File "/home/ec2-user/environment/slackapp-chatgpt/add_document.py", line 28, in initialize_vectorstore
    return Pinecone.from_existing_index(index_name, embeddings)
  File "/home/ec2-user/environment/slackapp-chatgpt/.venv/lib/python3.10/site-packages/langchain/vectorstores/pinecone.py", line 437, in from_existing_index
    pinecone_index = cls.get_pinecone_index(index_name, pool_threads)
  File "/home/ec2-user/environment/slackapp-chatgpt/.venv/lib/python3.10/site-packages/langchain/vectorstores/pinecone.py", line 354, in get_pinecone_index
    indexes = pinecone.list_indexes()  # checks if provided index exists
  File "/home/ec2-user/environment/slackapp-chatgpt/.venv/lib/python3.10/site-packages/pinecone/manage.py", line 185, in list_indexes
    response = api_instance.list_indexes()
  File "/home/ec2-user/environment/slackapp-chatgpt/.venv/lib/python3.10/site-packages/pinecone/core/client/api_client.py", line 776, in __call__
    return self.callable(self, *args, **kwargs)
  File "/home/ec2-user/environment/slackapp-chatgpt/.venv/lib/python3.10/site-packages/pinecone/core/client/api/index_operations_api.py", line 1130, in __list_indexes
    return self.call_with_http_info(**kwargs)
  File "/home/ec2-user/environment/slackapp-chatgpt/.venv/lib/python3.10/site-packages/pinecone/core/client/api_client.py", line 838, in call_with_http_info
    return self.api_client.call_api(
  File "/home/ec2-user/environment/slackapp-chatgpt/.venv/lib/python3.10/site-packages/pinecone/core/client/api_client.py", line 413, in call_api
    return self.__call_api(resource_path, method,
  File "/home/ec2-user/environment/slackapp-chatgpt/.venv/lib/python3.10/site-packages/pinecone/core/client/api_client.py", line 200, in __call_api
    response_data = self.request(
  File "/home/ec2-user/environment/slackapp-chatgpt/.venv/lib/python3.10/site-packages/pinecone/core/client/api_client.py", line 439, in request
    return self.rest_client.GET(url,
  File "/home/ec2-user/environment/slackapp-chatgpt/.venv/lib/python3.10/site-packages/pinecone/core/client/rest.py", line 236, in GET
    return self.request("GET", url,
  File "/home/ec2-user/environment/slackapp-chatgpt/.venv/lib/python3.10/site-packages/pinecone/core/client/rest.py", line 202, in request
    r = self.pool_manager.request(method, url,
  File "/home/ec2-user/environment/slackapp-chatgpt/.venv/lib/python3.10/site-packages/urllib3/_request_methods.py", line 110, in request
    return self.request_encode_url(
  File "/home/ec2-user/environment/slackapp-chatgpt/.venv/lib/python3.10/site-packages/urllib3/_request_methods.py", line 143, in request_encode_url
    return self.urlopen(method, url, **extra_kw)
  File "/home/ec2-user/environment/slackapp-chatgpt/.venv/lib/python3.10/site-packages/urllib3/poolmanager.py", line 443, in urlopen
    response = conn.urlopen(method, u.request_uri, **kw)
  File "/home/ec2-user/environment/slackapp-chatgpt/.venv/lib/python3.10/site-packages/urllib3/connectionpool.py", line 875, in urlopen
    return self.urlopen(
  File "/home/ec2-user/environment/slackapp-chatgpt/.venv/lib/python3.10/site-packages/urllib3/connectionpool.py", line 875, in urlopen
    return self.urlopen(
  File "/home/ec2-user/environment/slackapp-chatgpt/.venv/lib/python3.10/site-packages/urllib3/connectionpool.py", line 875, in urlopen
    return self.urlopen(
  File "/home/ec2-user/environment/slackapp-chatgpt/.venv/lib/python3.10/site-packages/urllib3/connectionpool.py", line 845, in urlopen
    retries = retries.increment(
  File "/home/ec2-user/environment/slackapp-chatgpt/.venv/lib/python3.10/site-packages/urllib3/util/retry.py", line 515, in increment
    raise MaxRetryError(_pool, url, reason) from reason  # type: ignore[arg-type]
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='controller.gcp-start.pinecone.io', port=443): Max retries exceeded with url: /databases (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7f527f8f9900>: Failed to resolve 'controller.gcp-start.pinecone.io' ([Errno -2] Name or service not known)"))
```

**Comment by os1ma** [comment]
ご質問ありがとうございます。

`controller.gcp-start.pinecone.io` の `gcp-start` の部分は、`.env` ファイルの `PINECONE_ENV` を読み込んで、以下の箇所で設定しています。

https://github.com/yoshidashingo/langchain-book/blob/f518007b8d64620ea491ea51acc1d88bd6b79ec4/chapter8/add_document.py#L23

`env` ファイルの `PINECONE_ENV` が、`gcp-starter` ではなく `gcp-start` となっている挙動にみえるので、この箇所をご確認ください。

https://github.com/yoshidashingo/langchain-book/blob/f518007b8d64620ea491ea51acc1d88bd6b79ec4/chapter8/.env.example#L12

よろしくお願いします！

**Comment by os1ma** [comment]
解決してよかったです！
